#!/bin/sh
set -e
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	DO \$\$
	BEGIN
	  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'grafana_ro') THEN
	    CREATE ROLE grafana_ro LOGIN PASSWORD '${GRAFANA_DB_PASSWORD}';
	  END IF;
	END
	\$\$;
	GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO grafana_ro;
	GRANT USAGE ON SCHEMA public TO grafana_ro;
	GRANT SELECT ON ALL TABLES IN SCHEMA public TO grafana_ro;
	ALTER DEFAULT PRIVILEGES FOR ROLE ${POSTGRES_USER} IN SCHEMA public GRANT SELECT ON TABLES TO grafana_ro;
EOSQL
