apiVersion: 1

datasources:
  - name: WealthTracker
    type: postgres
    access: proxy
    url: pgsql:5432
    user: grafana_ro
    isDefault: true
    jsonData:
      database: wealthtracker
      sslmode: disable
      postgresVersion: 1700
    secureJsonData:
      password: $GRAFANA_DB_PASSWORD
    editable: false
